domains = [{
    'name': 'satellite', 
    'ipc': 'None', 
    'problems': [
        ('satellite/domain.pddl', 'satellite/instances/pfile1.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile2.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile3.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile4.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile5.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile6.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile7.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile8.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile9.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile10.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile11.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile12.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile13.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile14.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile15.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile16.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile17.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile18.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile19.pddl'), 
        ('satellite/domain.pddl', 'satellite/instances/pfile20.pddl')
        ]}]