domains = [
    {'name': 'rover', 
     'ipc': 'None', 
     'problems': [
         ('rover/domain.pddl', 'rover/instances/pfile1.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile2.pddl'),
         ('rover/domain.pddl', 'rover/instances/pfile3.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile4.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile5.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile6.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile7.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile8.pddl'),
         ('rover/domain.pddl', 'rover/instances/pfile9.pddl'),
         ('rover/domain.pddl', 'rover/instances/pfile10.pddl'),
         ('rover/domain.pddl', 'rover/instances/pfile11.pddl'),
         ('rover/domain.pddl', 'rover/instances/pfile12.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile13.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile14.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile15.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile16.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile17.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile18.pddl'),
         ('rover/domain.pddl', 'rover/instances/pfile19.pddl'), 
         ('rover/domain.pddl', 'rover/instances/pfile20.pddl')
    ]}]